from typing import Protocol, Optional, List
from app.domain.entities import User, RawMaterial, Order, AuditLog

class IUserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    async def get_by_username(self, username: str) -> Optional[User]: ...
    async def create(self, user: User) -> User: ...

class IRawMaterialRepository(Protocol):
    async def get_by_id(self, material_id: int) -> Optional[RawMaterial]: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> List[RawMaterial]: ...
    async def create(self, material: RawMaterial) -> RawMaterial: ...
    async def update(self, material: RawMaterial) -> RawMaterial: ...
    async def delete(self, material_id: int) -> bool: ...

class IOrderRepository(Protocol):
    async def get_by_id(self, order_id: int) -> Optional[Order]: ...
    async def get_all(self, customer_id: Optional[int] = None, skip: int = 0, limit: int = 100) -> List[Order]: ...
    async def create(self, order: Order) -> Order: ...
    async def update_status(self, order_id: int, status: str) -> Optional[Order]: ...

class IAuditRepository(Protocol):
    async def create(self, log: AuditLog) -> AuditLog: ...
    async def get_all(self, limit: int = 100) -> List[AuditLog]: ...
